types:
    - blog:
          source: blogs/**/*.md
          primaryKey: id
          indexFields: [year, tags, author]

collections:
    - allBlogs:
          type: blog
          sortBy:
              - year: desc
    - blogsByAuthor:
          type: blog
          partitionBy: [tags, author]