sources:
    - blog:
        type: blog
        glob: blogs/**/*.md

types:
    - blog:
        primaryKey: id
        indexFields: [year, tags, author]
        contentType: markdown

collections:
    - allBlogs:
        type: blog
        sortBy:
            - year: desc
    - blogsByAuthor:
        type: blog
        partitionBy: [tags, author]